name: Valgrind

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: make test
      run: |
        make test -C 3_Implementation/
        valgrind ./3_Implementation/build/Test_Customer.out
        gcc src/manage.c test/test_manage.c  -Iinc -o build/Test_Customer.out --ggdb3 -lcunit
./build/Test_Customer.out
        
